HTTPCORE-193-fulllog

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,18 +22,18 @@ jobs:
       - name: Check
         uses: actions/checkout@v3
         with:
-          ref: 08d9c3c30d57def4963d0807bce5f3023f5fcb35
+          ref: 12a10354d87d75544de5b57dccb7137a40157a22
   
       - name: Test with Maven
         run: | 
-              for i in {1..100}; do mvn test -Dtest=org.apache.http.impl.nio.reactor.TestDefaultIOReactorsSSL -Dsurefire.failIfNoSpecifiedTests=false -fae; done#>>test_log_HTTPCORE-193.txt; done
-              echo "Maven tests completed." 
-      # - name: Upload Test Log 
-      #   if: always() 
-      #   uses: actions/upload-artifact@v2 
-      #   with: 
-      #     name: test_log_HTTPCORE-193
-      #     path: test_log_HTTPCORE-193.txt
+              for i in {1..100}; do echo "Running test iteration $i" mvn test -Dtest=org.apache.http.impl.nio.reactor.TestDefaultIOReactorsSSL -Dsurefire.failIfNoSpecifiedTests=false -fae>>test_log_HTTPCORE-193.txt || echo "Test iteration $i failed">>test_log_HTTPCORE-193.txt; done
+              
+      - name: Upload Test Log 
+        if: always() 
+        uses: actions/upload-artifact@v2 
+        with: 
+          name: test_log_HTTPCORE-193
+          path: test_log_HTTPCORE-193.txt
 
       - name: Nondex
         run: mvn edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.http.impl.nio.reactor.TestDefaultIOReactorsSSL -Dsurefire.failIfNoSpecifiedTests=false -DnondexRuns=100
